//"use client";
import "../styles/globals.css";

import Nav from "../components/Nav";
import Content from "@/components/Content";
import { motion } from "framer-motion";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full ">
        <Content>
          <div className="h-full bg-gradient-to-t from-purple-600 to-pink-800 flex flex-col">
            <Nav>{children}</Nav>
            <div className="h-full flex items-center justify-center ">
              {children}
            </div>
          </div>
        </Content>
      </body>
    </html>
  );
}
